// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_mainPanel = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_mainPanel, 320);
    lv_obj_set_height(ui_mainPanel, 240);
    lv_obj_set_align(ui_mainPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_mainPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_mainPanel, lv_color_hex(0x05063E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mainPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WtmpARC = lv_arc_create(ui_mainPanel);
    lv_obj_set_width(ui_WtmpARC, 210);
    lv_obj_set_height(ui_WtmpARC, 210);
    lv_obj_set_x(ui_WtmpARC, 1);
    lv_obj_set_y(ui_WtmpARC, 31);
    lv_obj_set_align(ui_WtmpARC, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_WtmpARC, 100, 300);
    lv_arc_set_value(ui_WtmpARC, 215);

    lv_obj_set_style_arc_color(ui_WtmpARC, lv_color_hex(0x19ACBA), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_WtmpARC, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_wifiLabel = lv_label_create(ui_mainPanel);
    lv_obj_set_width(ui_wifiLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wifiLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wifiLabel, -110);
    lv_obj_set_y(ui_wifiLabel, -80);
    lv_obj_set_align(ui_wifiLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_wifiLabel, "Offline");
    lv_obj_set_style_text_font(ui_wifiLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimeLabel = lv_label_create(ui_mainPanel);
    lv_obj_set_width(ui_TimeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TimeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TimeLabel, 100);
    lv_obj_set_y(ui_TimeLabel, -95);
    lv_obj_set_align(ui_TimeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TimeLabel, "00:00");
    lv_obj_set_style_text_letter_space(ui_TimeLabel, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_TimeLabel, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_TimeLabel, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TimeLabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AutoManual = lv_label_create(ui_mainPanel);
    lv_obj_set_width(ui_AutoManual, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AutoManual, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AutoManual, -110);
    lv_obj_set_y(ui_AutoManual, -100);
    lv_obj_set_align(ui_AutoManual, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AutoManual, "Auto");

    ui_Label1 = lv_label_create(ui_mainPanel);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 117);
    lv_obj_set_y(ui_Label1, -54);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "OFF");
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WtmpLabel = lv_label_create(ui_mainPanel);
    lv_obj_set_width(ui_WtmpLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WtmpLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WtmpLabel, 0);
    lv_obj_set_y(ui_WtmpLabel, -35);
    lv_obj_set_align(ui_WtmpLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WtmpLabel, "0 °C");
    lv_obj_set_style_text_font(ui_WtmpLabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TmpLabel = lv_label_create(ui_mainPanel);
    lv_obj_set_width(ui_TmpLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TmpLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TmpLabel, 0);
    lv_obj_set_y(ui_TmpLabel, -5);
    lv_obj_set_align(ui_TmpLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TmpLabel, "0 °C");
    lv_obj_set_style_text_font(ui_TmpLabel, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HmdLabel = lv_label_create(ui_mainPanel);
    lv_obj_set_width(ui_HmdLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HmdLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HmdLabel, 0);
    lv_obj_set_y(ui_HmdLabel, 25);
    lv_obj_set_align(ui_HmdLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HmdLabel, "0 %");

    ui_buttonpanel = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_buttonpanel, 110);
    lv_obj_set_height(ui_buttonpanel, 75);
    lv_obj_set_x(ui_buttonpanel, 0);
    lv_obj_set_y(ui_buttonpanel, 80);
    lv_obj_set_align(ui_buttonpanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_buttonpanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HeatButton = lv_btn_create(ui_buttonpanel);
    lv_obj_set_width(ui_HeatButton, 100);
    lv_obj_set_height(ui_HeatButton, 30);
    lv_obj_set_x(ui_HeatButton, 0);
    lv_obj_set_y(ui_HeatButton, -17);
    lv_obj_set_align(ui_HeatButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HeatButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_HeatButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label5 = lv_label_create(ui_HeatButton);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "Options");

    ui_ProgButton = lv_btn_create(ui_buttonpanel);
    lv_obj_set_width(ui_ProgButton, 100);
    lv_obj_set_height(ui_ProgButton, 30);
    lv_obj_set_x(ui_ProgButton, 0);
    lv_obj_set_y(ui_ProgButton, 18);
    lv_obj_set_align(ui_ProgButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ProgButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ProgButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label6 = lv_label_create(ui_ProgButton);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Programs");

    lv_obj_add_event_cb(ui_HeatButton, ui_event_HeatButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ProgButton, ui_event_ProgButton, LV_EVENT_ALL, NULL);

    ui_Screen_Number = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Screen_Number, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Screen_Number, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Screen_Number, 240);
    lv_obj_set_y(ui_Screen_Number, 320);
    lv_obj_set_align(ui_Screen_Number, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Screen_Number, "0");

}
