// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HeatPanel = lv_obj_create(ui_Screen3);
    lv_obj_set_width(ui_HeatPanel, 320);
    lv_obj_set_height(ui_HeatPanel, 240);
    lv_obj_set_align(ui_HeatPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_HeatPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HeatPanel, lv_color_hex(0x06053E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HeatPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Back2Button = lv_btn_create(ui_HeatPanel);
    lv_obj_set_width(ui_Back2Button, 100);
    lv_obj_set_height(ui_Back2Button, 50);
    lv_obj_set_x(ui_Back2Button, 0);
    lv_obj_set_y(ui_Back2Button, 80);
    lv_obj_set_align(ui_Back2Button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Back2Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Back2Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Back2Label = lv_label_create(ui_Back2Button);
    lv_obj_set_width(ui_Back2Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Back2Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Back2Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Back2Label, "Back");

    ui_HeatSetting = lv_dropdown_create(ui_HeatPanel);
    lv_dropdown_set_options(ui_HeatSetting, "Auto Heater\nGas heater\n");
    lv_obj_set_width(ui_HeatSetting, 150);
    lv_obj_set_height(ui_HeatSetting, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HeatSetting, 0);
    lv_obj_set_y(ui_HeatSetting, -40);
    lv_obj_set_align(ui_HeatSetting, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HeatSetting, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_HeatScreenLabel = lv_label_create(ui_HeatPanel);
    lv_obj_set_width(ui_HeatScreenLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HeatScreenLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HeatScreenLabel, 0);
    lv_obj_set_y(ui_HeatScreenLabel, -90);
    lv_obj_set_align(ui_HeatScreenLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HeatScreenLabel, "Heater settings");
    lv_obj_set_style_text_font(ui_HeatScreenLabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConnectedDeviceButton = lv_btn_create(ui_HeatPanel);
    lv_obj_set_width(ui_ConnectedDeviceButton, 100);
    lv_obj_set_height(ui_ConnectedDeviceButton, 50);
    lv_obj_set_x(ui_ConnectedDeviceButton, -70);
    lv_obj_set_y(ui_ConnectedDeviceButton, 15);
    lv_obj_set_align(ui_ConnectedDeviceButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ConnectedDeviceButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ConnectedDeviceButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label3 = lv_label_create(ui_ConnectedDeviceButton);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Connected\n    Device");

    ui_BIOS = lv_btn_create(ui_HeatPanel);
    lv_obj_set_width(ui_BIOS, 100);
    lv_obj_set_height(ui_BIOS, 50);
    lv_obj_set_x(ui_BIOS, 70);
    lv_obj_set_y(ui_BIOS, 15);
    lv_obj_set_align(ui_BIOS, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BIOS, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BIOS, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BIOSLabel = lv_label_create(ui_BIOS);
    lv_obj_set_width(ui_BIOSLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BIOSLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BIOSLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BIOSLabel, "Service\nOptions");

    ui_BiosBool = lv_label_create(ui_BIOS);
    lv_obj_set_width(ui_BiosBool, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BiosBool, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BiosBool, 68);
    lv_obj_set_y(ui_BiosBool, 91);
    lv_obj_set_align(ui_BiosBool, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BiosBool, "0");

    lv_obj_add_event_cb(ui_Back2Button, ui_event_Back2Button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HeatSetting, ui_event_HeatSetting, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ConnectedDeviceButton, ui_event_ConnectedDeviceButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BIOS, ui_event_BIOS, LV_EVENT_ALL, NULL);

}
