// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainPanel = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_MainPanel, 260);
    lv_obj_set_height(ui_MainPanel, 240);
    lv_obj_set_x(ui_MainPanel, 30);
    lv_obj_set_y(ui_MainPanel, 0);
    lv_obj_set_align(ui_MainPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MainPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MainPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MainPanel, lv_color_hex(0x0A2BCF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_MainPanel, lv_color_hex(0x0A2BCF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MainPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Wifiimage = lv_img_create(ui_MainPanel);
    lv_obj_set_width(ui_Wifiimage, 40);
    lv_obj_set_height(ui_Wifiimage, 40);
    lv_obj_set_x(ui_Wifiimage, 100);
    lv_obj_set_y(ui_Wifiimage, -90);
    lv_obj_set_align(ui_Wifiimage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Wifiimage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Wifiimage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BatteryImage = lv_img_create(ui_MainPanel);
    lv_obj_set_width(ui_BatteryImage, 40);
    lv_obj_set_height(ui_BatteryImage, 40);
    lv_obj_set_x(ui_BatteryImage, 50);
    lv_obj_set_y(ui_BatteryImage, -90);
    lv_obj_set_align(ui_BatteryImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BatteryImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BatteryImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ButteryLabel = lv_label_create(ui_MainPanel);
    lv_obj_set_width(ui_ButteryLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ButteryLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ButteryLabel, 5);
    lv_obj_set_y(ui_ButteryLabel, -87);
    lv_obj_set_align(ui_ButteryLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ButteryLabel, "17 %");
    lv_obj_set_style_text_color(ui_ButteryLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ButteryLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ButteryLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SidePanel = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_SidePanel, 60);
    lv_obj_set_height(ui_SidePanel, 240);
    lv_obj_set_x(ui_SidePanel, -130);
    lv_obj_set_y(ui_SidePanel, 0);
    lv_obj_set_align(ui_SidePanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SidePanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SidePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SidePanel, lv_color_hex(0x0A8AED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SidePanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SidePanel, lv_color_hex(0x0A8AED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SidePanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Home = lv_img_create(ui_SidePanel);
    lv_obj_set_width(ui_Home, 40);
    lv_obj_set_height(ui_Home, 40);
    lv_obj_set_x(ui_Home, 0);
    lv_obj_set_y(ui_Home, -94);
    lv_obj_set_align(ui_Home, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Home, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Home, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Back = lv_img_create(ui_SidePanel);
    lv_obj_set_width(ui_Back, 40);
    lv_obj_set_height(ui_Back, 40);
    lv_obj_set_x(ui_Back, 0);
    lv_obj_set_y(ui_Back, -47);
    lv_obj_set_align(ui_Back, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Back, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Back, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Save = lv_img_create(ui_SidePanel);
    lv_obj_set_width(ui_Save, 40);
    lv_obj_set_height(ui_Save, 40);
    lv_obj_set_align(ui_Save, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Save, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Save, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Menu = lv_img_create(ui_SidePanel);
    lv_obj_set_width(ui_Menu, 40);
    lv_obj_set_height(ui_Menu, 40);
    lv_obj_set_x(ui_Menu, 0);
    lv_obj_set_y(ui_Menu, 47);
    lv_obj_set_align(ui_Menu, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Menu, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Menu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Switch = lv_img_create(ui_SidePanel);
    lv_obj_set_width(ui_Switch, 40);
    lv_obj_set_height(ui_Switch, 40);
    lv_obj_set_x(ui_Switch, 0);
    lv_obj_set_y(ui_Switch, 94);
    lv_obj_set_align(ui_Switch, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Switch, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Switch, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_FunctionPanel = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_FunctionPanel, 255);
    lv_obj_set_height(ui_FunctionPanel, 185);
    lv_obj_set_x(ui_FunctionPanel, 30);
    lv_obj_set_y(ui_FunctionPanel, 24);
    lv_obj_set_align(ui_FunctionPanel, LV_ALIGN_CENTER);
    lv_obj_set_scroll_dir(ui_FunctionPanel, LV_DIR_RIGHT);
    lv_obj_set_style_radius(ui_FunctionPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_FunctionPanel, lv_color_hex(0x0A2BCF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_FunctionPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_FunctionPanel, lv_color_hex(0x0A2BCF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_FunctionPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button1 = lv_btn_create(ui_FunctionPanel);
    lv_obj_set_width(ui_Button1, 100);
    lv_obj_set_height(ui_Button1, 50);
    lv_obj_set_x(ui_Button1, -40);
    lv_obj_set_y(ui_Button1, 1);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_Button1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);

    ui_Button2 = lv_btn_create(ui_FunctionPanel);
    lv_obj_set_width(ui_Button2, 60);
    lv_obj_set_height(ui_Button2, 60);
    lv_obj_set_x(ui_Button2, 54);
    lv_obj_set_y(ui_Button2, 0);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image8 = lv_img_create(ui_Button2);
    lv_obj_set_width(ui_Image8, 60);
    lv_obj_set_height(ui_Image8, 60);
    lv_obj_set_align(ui_Image8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Image8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Image8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Image8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor(ui_Image8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_Image8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel4 = lv_obj_create(ui_FunctionPanel);
    lv_obj_set_width(ui_Panel4, 100);
    lv_obj_set_height(ui_Panel4, 50);
    lv_obj_set_x(ui_Panel4, -2);
    lv_obj_set_y(ui_Panel4, 62);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label3 = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);

    ui_TextArea1 = lv_textarea_create(ui_Screen1);
    lv_obj_set_width(ui_TextArea1, 150);
    lv_obj_set_height(ui_TextArea1, 70);
    lv_obj_set_x(ui_TextArea1, 83);
    lv_obj_set_y(ui_TextArea1, 72);
    lv_obj_set_align(ui_TextArea1, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea1, "Placeholder...");



    ui_Keyboard2 = lv_keyboard_create(ui_Screen1);
    lv_obj_set_width(ui_Keyboard2, 300);
    lv_obj_set_height(ui_Keyboard2, 120);
    lv_obj_set_x(ui_Keyboard2, -8);
    lv_obj_set_y(ui_Keyboard2, 76);
    lv_obj_set_align(ui_Keyboard2, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_TextArea1, ui_event_TextArea1, LV_EVENT_ALL, NULL);

}
