// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_mainPanel;
lv_obj_t * ui_WtmpARC;
lv_obj_t * ui_wifiLabel;
lv_obj_t * ui_TimeLabel;
lv_obj_t * ui_AutoManual;
lv_obj_t * ui_Label1;
lv_obj_t * ui_WtmpLabel;
lv_obj_t * ui_TmpLabel;
lv_obj_t * ui_HmdLabel;
lv_obj_t * ui_buttonpanel;
void ui_event_HeatButton(lv_event_t * e);
lv_obj_t * ui_HeatButton;
lv_obj_t * ui_Label5;
void ui_event_ProgButton(lv_event_t * e);
lv_obj_t * ui_ProgButton;
lv_obj_t * ui_Label6;
lv_obj_t * ui_Screen_Number;


// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
lv_obj_t * ui_Screen2;
lv_obj_t * ui_ProgPanel;
void ui_event_wtmpSLider(lv_event_t * e);
lv_obj_t * ui_wtmpSLider;
lv_obj_t * ui_ProgTmpLabel;
void ui_event_Button3(lv_event_t * e);
lv_obj_t * ui_Button3;
lv_obj_t * ui_Label15;
lv_obj_t * ui_Roller1;
lv_obj_t * ui_Roller2;
lv_obj_t * ui_TmpChart;
lv_obj_t * ui_WTMPSliderLable;
void ui_event_SaveButton(lv_event_t * e);
lv_obj_t * ui_SaveButton;
lv_obj_t * ui_Label2;
void ui_event_SaveBool(lv_event_t * e);
lv_obj_t * ui_SaveBool;


// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
lv_obj_t * ui_Screen3;
lv_obj_t * ui_HeatPanel;
void ui_event_Back2Button(lv_event_t * e);
lv_obj_t * ui_Back2Button;
lv_obj_t * ui_Back2Label;
void ui_event_HeatSetting(lv_event_t * e);
lv_obj_t * ui_HeatSetting;
lv_obj_t * ui_HeatScreenLabel;
void ui_event_ConnectedDeviceButton(lv_event_t * e);
lv_obj_t * ui_ConnectedDeviceButton;
lv_obj_t * ui_Label3;
void ui_event_BIOS(lv_event_t * e);
lv_obj_t * ui_BIOS;
lv_obj_t * ui_BIOSLabel;
lv_obj_t * ui_BiosBool;


// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
lv_obj_t * ui_Screen4;
lv_obj_t * ui_devicePanel;
void ui_event_BackButtonScreen4(lv_event_t * e);
lv_obj_t * ui_BackButtonScreen4;
lv_obj_t * ui_Label4;
lv_obj_t * ui_Panel1;
lv_obj_t * ui_DeviceTemplate1;
lv_obj_t * ui_DeviceTemplateMAC1;
lv_obj_t * ui_DeviceTemplateName1;
lv_obj_t * ui_Temptemplate1;
lv_obj_t * ui_CeliusLabel1;
lv_obj_t * ui_DeviceTemplate2;
lv_obj_t * ui_DeviceTemplateMAC2;
lv_obj_t * ui_DeviceTemplateName2;
lv_obj_t * ui_Temptemplate2;
lv_obj_t * ui_CeliusLabel2;
lv_obj_t * ui_DeviceTemplate3;
lv_obj_t * ui_DeviceTemplateMAC3;
lv_obj_t * ui_DeviceTemplateName3;
lv_obj_t * ui_Temptemplate3;
lv_obj_t * ui_CeliusLabel3;
lv_obj_t * ui_DeviceTemplate4;
lv_obj_t * ui_DeviceTemplateMAC4;
lv_obj_t * ui_DeviceTemplateName4;
lv_obj_t * ui_Temptemplate4;
lv_obj_t * ui_CeliusLabel4;


// SCREEN: ui_Screen5
void ui_Screen5_screen_init(void);
lv_obj_t * ui_Screen5;
void ui_event_Panel2(lv_event_t * e);
lv_obj_t * ui_Panel2;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_HeatButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_MOVE_LEFT, 100, 0, &ui_Screen3_screen_init);
        lv_label_set_text(ui_Screen_Number,"2");
    }
}
void ui_event_ProgButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 100, 0, &ui_Screen2_screen_init);
    }
}
void ui_event_wtmpSLider(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        SetWantedTMPSCR2(e);
        lv_label_set_text(ui_Screen_Number,"1");
    }
}
void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_MOVE_LEFT, 100, 0, &ui_Screen1_screen_init);
         lv_label_set_text(ui_Screen_Number,"0");
    }
}
void ui_event_SaveButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        _ui_label_set_property(ui_SaveBool, _UI_LABEL_PROPERTY_TEXT, "1");
    }
}
void ui_event_SaveBool(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        _ui_label_set_property(ui_SaveBool, _UI_LABEL_PROPERTY_TEXT, "1");
    }
}
void ui_event_Back2Button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 100, 0, &ui_Screen1_screen_init);
        lv_label_set_text(ui_Screen_Number,"0");
    }
}
void ui_event_HeatSetting(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ChangeHeatSetting(e);
    }
}
void ui_event_ConnectedDeviceButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Screen4, LV_SCR_LOAD_ANIM_MOVE_LEFT, 100, 0, &ui_Screen4_screen_init);
        lv_label_set_text(ui_Screen_Number,"3");
    }
}
void ui_event_BIOS(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        _ui_label_set_property(ui_BiosBool, _UI_LABEL_PROPERTY_TEXT, "1");
    }
}
void ui_event_BackButtonScreen4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 100, 0, &ui_Screen3_screen_init);
         lv_label_set_text(ui_Screen_Number,"2");
    }
}
void ui_event_Panel2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESS_LOST) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Screen1_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui_Screen2_screen_init();
    ui_Screen3_screen_init();
    ui_Screen4_screen_init();
    ui_Screen5_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
