// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "lv_i18n.h"
#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;

extern lv_obj_t * ui_MainPanel;
extern lv_obj_t * ui_Wifiimage;
extern lv_obj_t * ui_BatteryImage;
extern lv_obj_t * ui_ButteryLabel;

extern lv_obj_t * ui_SidePanel;
extern lv_obj_t * ui_Home;
extern lv_obj_t * ui_Back;
extern lv_obj_t * ui_Save;
extern lv_obj_t * ui_Menu;
extern lv_obj_t * ui_Switch;

extern lv_obj_t * ui_FunctionPanel;

extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Label3;
void ui_event_TextArea1(lv_event_t * e);
extern lv_obj_t * ui_TextArea1;
extern lv_obj_t * ui_Keyboard2;
extern lv_obj_t * ui____initial_actions0;








void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
